services:
  postgres:
    image: postgres:16-alpine
    container_name: election_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: election
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: