spring:
  application:
    name: Anonymous Election
  datasource:
    # Connects to localhost:5432 (your Docker container)
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5433}/${PGDATABASE:election}
    username: ${PGUSER:dev}
    password: ${PGPASSWORD:dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    # "update": Automatically creates/updates tables based on your Java code
    hibernate:
      ddl-auto: update
    # Shows the SQL queries in the console (useful for debugging)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true